using System;
using System.Runtime.Serialization;

namespace Tamasi.Shared.Framework
{
	/// <summary>
	/// Represents an error generated by this scarab app
	/// </summary>
	[Serializable]
	public class ScarabException : ApplicationException
	{
		public ScarabException( Int64 eventID, string format, params object[] args )
			: base( string.Format( format, args ) )
		{
			this.EventID = eventID;
		}

		public ScarabException( string format, params object[] args )
			: base( string.Format( format, args ) )
		{

		}

		public ScarabException( Exception e )
			: base( "ScarabException", e )
		{

		}

		public Int64 EventID { get; private set; }

		public override void GetObjectData( SerializationInfo info, StreamingContext context )
		{
			base.GetObjectData( info, context );
		}
	}

	/// <summary>
	/// Represents an error generated by this scarab app
	/// </summary>
	[Serializable]
	public class ScarabKnownIssueException : ScarabException
	{
		public ScarabKnownIssueException( string format, params object[] args )
			: base( string.Format( format, args ) )
		{

		}

		public ScarabKnownIssueException( Exception e )
			: base( "ScarabException", e )
		{

		}
	}
}
