using System;
using System.Diagnostics;

namespace Tamasi.Shared.WinFramework
{
	/// <summary>
	/// Embodies same data as the OSGSA Shared Table [base].[BuildFlavor]
	/// </summary>
	public class TargetBuildFlavorBase
	{
		#region Fields and Constructors

		private readonly string procArchString;
		private readonly string chunkName;
		private readonly string buildTypeString;
		//private readonly string languageSpecification;
		private readonly Int32 buildFlavorID;

		public TargetBuildFlavorBase
		(
			string procArchString,
			string chunkName,
			string buildTypeString )
		{
			Debug.Assert( !string.IsNullOrWhiteSpace( procArchString ) );
			Debug.Assert( !string.IsNullOrWhiteSpace( chunkName ) );
			Debug.Assert( !string.IsNullOrWhiteSpace( buildTypeString ) );

			this.procArchString = procArchString;
			this.chunkName = chunkName;
			this.buildTypeString = buildTypeString;

			this.buildFlavorID = KeyGen.BuildFlavorID
			(
				this.procArchString,
				this.chunkName,
				this.buildTypeString
			);
		}

		#endregion
	
		#region Properties

		/// <summary>
		/// Synonymous with the OSGSA Shared Table [base].[BuildFlavor].[BuildFlavorID],
		/// generated by [base].[KeyGen_BuildFlavorID]
		/// </summary>
		public Int32 BuildFlavorID
		{
			get { return this.buildFlavorID; }
		}

		public string ProcArchString
		{
			get { return this.procArchString; }
		}

		public string ChunkName
		{
			get { return this.chunkName; }
		}

		public string BuildTypeString
		{
			get { return this.buildTypeString; }
		}

		#endregion
	}
}
